{{- if .Values.job.enabled -}}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-job
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: job
    {{ include "bkrepo.labelValues.scope" . }}: {{ include "bkrepo.labelValues.scope.backend" . }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: job
  replicas: {{ default 1 .Values.job.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: job
        {{ include "bkrepo.labelValues.scope" . }}: {{ include "bkrepo.labelValues.scope.backend" . }}
        {{- if .Values.job.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.job.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "bkrepo.serviceAccountName" . }}
      {{- include "bkrepo.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.job.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.job.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.job.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.job.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if eq .Values.persistence.accessMode "ReadWriteOnce" }}
        podAffinity: {{- include "common.affinities.pods" (dict "type" "soft" "component" "repository" "context" $) | nindent 10 }}
        {{- else }}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.repository.podAffinityPreset "component" "job" "context" $) | nindent 10 }}
        {{- end }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.job.podAntiAffinityPreset "component" "job" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.job.nodeAffinityPreset.type "key" .Values.job.nodeAffinityPreset.key "values" .Values.job.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.job.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.job.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.job.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.job.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.job.priorityClassName }}
      priorityClassName: {{ .Values.job.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.job.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.job.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: job
          image: {{ include "bkrepo.images.image" ( dict "imageRoot" .Values.job.image "global" .Values.global "bkrepo" .Values.common) }}
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          {{- if .Values.job.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.job.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.job.resources }}
          resources: {{- toYaml .Values.job.resources | nindent 12 }}
          {{- end }}
          env:
            - name: BK_REPO_JVM_OPTION
              value: {{ .Values.common.jvmOption }}
            - name: BK_REPO_PROFILE
              value: {{ .Values.common.springProfile }}
            - name: BK_REPO_SERVICE_PREFIX
              value: {{ include "common.names.fullname" . }}-
          ports:
            - name: http
              containerPort: 25907
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/livenessState
              port: http
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readinessState
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.common.mountPath }}
      volumes:
        - name: storage
          {{- if .Values.common.config.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-nfs-pvc
          {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "common.names.fullname" . }}-storage{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
