[metadata]
standalonemode = true
# 任务ID，standalone模式可以忽略
taskID = "#{[taskId]}"
# 描述，standalone模式可以忽略
description = "This is a simple reference project configuration."
# 无需修改
analysistype = "Artifact"
# 无需修改
analysissubtype = "BinaryPackage"

[toparse]
[[toparse.binarypackage]]
# filename 输入文件路径，相对地址
filename = "./#{[inputFile]}"

[output]
[output.json]
# json 输出目录，会自动创建目录
path = "./#{[outputDir]}"
# 过滤列表，不输出某些分析项目
blacklist = ["file_items"]

# 无需修改
[output.log]
loglevel = "INFO"
logfile = "./sysauditor.log"

# 无需修改
[auditor]
include_text = true
include_binary = true

[sysauditor.nvtools]
enabled = "#{[nvToolsEnabled]}"
username = "#{[nvToolsUsername]}"
key = "#{[nvToolsKey]}"
host = "#{[nvToolsHost]}"
